### ISSUE TITLE
vtk modules with VTKCell input ports

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1032] opened 2015-03-26 15:46 UTC
Follows up on [comments on c880fd4](https://github.com/VisTrails/VisTrails/commit/c880fd468295844e3ff694303d4c4c36743ec8fb#commitcomment-10402363), see also #1030

Some vtk modules have VTKCell input ports.
* This means that vtk can't be loaded without the spreadsheet
* These modules should probably be SpreadsheetCell subclasses themselves
* No module currently outputs VTKCell

Also, even with the backwards pipeline and using a PythonSource to cast, vtkImageViewer2 doesn't seem to work:
![screenshot](https://cloud.githubusercontent.com/assets/426784/6850046/0c702538-d3ad-11e4-9ec9-d3d81ba978b8.png)

**Comment by rexissimus** [comment] 2015-03-26 23:23
7eade15486b3acae771c125e7bb9e036a7c84c44 adds back the Instance port on VTKCell. I also cannot figure out how to use this. These modules are VTK classes and cannot be made into Spreadsheet Cells easily. They seem to be convenience classes for doing specific interactive things, so I am not sure they are really needed. @dakoop, do you have an idea how this should work?

**Comment by remram44** [comment] 2015-03-27 14:27
If the module doesn't work and requires horrible regressions to exist, I suggest simply removing it.

**Comment by rexissimus** [comment] 2015-03-27 15:38
These are the affected classes:

* vtkRenderViewBase
* vtkExporter
* vtkImageViewer2
* vtkOpenGLExtensionManager
* vtkRenderer

I was finally able to get vtkExporter on the terminator:Isosurface pipeline to work by making it call methods last (you also have to set prefix first and then Write). Is this class not needed? Are there other ways to write data files? Can this be done with output modules yet?

If we can remove this, we can also remove:
* The Instance output on VTKCell
* The abstract VTKCell
* Using VTKCell as a port

**Comment by remram44** [comment] 2015-03-27 18:15
I'd very much like to see output modules everywhere (yes, they do work) but they can probably come later.

* `vtkRenderer` definitely does not need a VTKCell input, we already have the AddRenderer port on VTKCell.
* I do not see `vtkExporter`.
* `vtkRenderViewBase` and `vtkRenderView` might not be useful?
* `vtkOpenGLExtensionManager` and `vtkImageViewer2` seem unusable anyway.

**Comment by rexissimus** [comment] 2015-03-28 16:47
vtkExporter is the parent class for several exporter classes. It looks like we would want to keep these. Should we try to create output modes for all of them? Should we ignore them for now and do this in a later release?

**Comment by remram44** [comment] 2015-03-28 20:50
Exporting classes shouldn't need a spreadsheet object plugged into them. That doesn't make sense.

We definitely need the file-writing modules to work, be there output modules or not. How did it all work before?

**Comment by rexissimus** [comment] 2015-03-30 11:23
cc @dakoop

> Exporting classes shouldn't need a spreadsheet object plugged into them. That doesn't make sense.

The exporters seem to require a vtkRenderView which is what VTKCell wraps. My guess is using the VTKCell was the simplest way to access the view without having a separate module for this. Just append an exporter module on VTKCell and write the output. We could perhaps make the exporters take a vtkRenderer and create the view themselves offscreen or in a standalone window?

> We definitely need the file-writing modules to work, be there output modules or not. How did it all work before?
> 
They still work just like before. Except in details, like the abstract VTKCell modules that is needed because the spec does not support conditional ports.

**Comment by remram44** [comment] 2015-03-30 20:29
There need to be a way to export images from VisTrails without the need for the spreadsheet.

**Comment by vistrails-dev** [comment] 2015-03-30 21:36
> There need to be a way to export images from VisTrails without the need for the spreadsheet.

Dos not vtkRendererToFile do that?

Also, I think VTKRenderOffscreen does the same thing and is probably redundant now?

The problem is the vtkExporter subclasses which can write different kinds of data from a vtkRendererView:
http://www.vtk.org/doc/nightly/html/classvtkExporter.html#details

**Comment by rexissimus** [comment] 2015-04-02 13:57
VTKCell ports are removed by 2f38d553bb31c32b02475d3502e9bf927ec3b21b. vtkExporter classes now take a vtkRenderer module as input and create their own offscreen vtkRenderView. There are also upgrades to fix existing workflows.

**Comment by remram44** [comment] 2015-04-02 15:22
I still see VTKCell; do I have to delete the `vtk-spec-5_10_0.xml` in `.vistrails`? Is that going to happen for every change in the VTK package's code?

**Comment by rexissimus** [comment] 2015-04-02 15:32
Yes, i forgot to mention that. You are right, we should append the VTK package version to the filename so that it automatically gets recomputed for future versions of the VTK package.

**Comment by remram44** [comment] 2015-04-02 15:39
Do you have an example that works? I connected vtkImageReader to vtkImageViewer2, but it doesn't produce any output at all. Should vtkImageViewer2 be simply removed?

**Comment by rexissimus** [comment] 2015-04-02 15:53
Try vtkOBJExporter. Connect it to a vtkRenderer. Set "FilePrefix" first and then set "Write" to True.

I am not sure how vtkImageViewer2 works, it is probably not useful. I guess we could blacklist all affected classes except vtkExporter and vtkRenderer?

**Comment by rexissimus** [comment] 2015-04-07 15:45
I found a working vtkImageViewer2 example:
    Connect vtkJPEGReader(File="somefile.jpg") -> vtkImageViewer2

Different output types:
* call vtkImageViewer2.Render() to render in separate window.
* connect Render output to a vtkRenderView[Base] to render in separate window. This is not useful in vistrails, so they should be removed.
* connect Render output to a VTKCell to render in spreadsheet.

Having a VTKCell or vtkRenderer as input does not seem necessary for vtkImageReader2 so it has been removed.

VTKOpenGLExtensionManager requires a vtkRenderWindow and is used to add OpenGL extensions to a RenderWindow. This does not seem to fit in a vistrails workflow so I am removing it.

This is fixed in commit 9b8bc082bcd540cb687dea9b7a109d0d99ddc67d.

**Closed** 2015-04-08 18:04 UTC
Labels: +bug, packages, vtk, _major
