### ISSUE TITLE
Exception from JobMonitor

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#975] opened 2014-12-10 21:12 UTC
```
Traceback (most recent call last):
  File "vistrails/gui/vistrails_window.py", line 1946, in method
    getattr(obj, method_name)()
  File "vistrails/gui/vistrail_view.py", line 1084, in execute
    view.execute()
  File "vistrails/gui/pipeline_view.py", line 3603, in execute
    self.controller.execute_user_workflow()
  File "vistrails/gui/vistrail_controller.py", line 451, in execute_user_workflow
    self.jobMonitor.finishWorkflow()
  File "vistrails/core/vistrail/job.py", line 505, in finishWorkflow
    if self.callback:
ReferenceError: weakly-referenced object no longer exists
```

I don't have the exact steps to reproduce yet, this seems to have something to do with closing workflows.

**Comment by remram44** [comment] 2015-02-25 16:27
Ran into this again!

**Comment by rexissimus** [comment] 2015-03-11 15:42
Fixed the ReferenceError with 2e6d0d4c918c89287da88aa175dddf328d00b844. But this should not happen. Are there running jobs missing in the job list? The callback refers to a Running Job widget so I don't think deleting the spreadsheet sheet should make a difference.

**Comment by remram44** [comment] 2015-03-11 17:16
Deleting the sheet ensures that the weakly referenced object dies, allowing the GC to make it invalid.

Maybe what you meant is "self.callback is not None"? I don't really know what happens there.

**Comment by rexissimus** [comment] 2015-03-13 10:57
This should be fixed by c882102c75db3bcda0259729694eb269b3983690. The reference error was probably caused by the wrong widget being deleted.

**Closed** 2015-03-25 13:21 UTC
Labels: +bug, @pending-review, core, _major

**Comment by remram44** [comment] 2015-04-06 18:22
I did a pass on the weakref usage in job.py with dcca2109. But really, I'm not sure why that reference need to be weak at all.

**Comment by rexissimus** [comment] 2015-04-06 18:30
I think the weakref can be removed. The jobs used to be saved at shutdown where the view may have been released but that is not the case anymore.
