### ISSUE TITLE
Modules are not sized the right way initially for portspecs

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1121] opened 2015-08-10 17:46 UTC
When loading a pipeline, modules that have port specs might not be large enough to show every port. Changing the visibility of any port on that module resizes it so all ports fit.

![portspec-sizing](https://cloud.githubusercontent.com/assets/426784/9178595/fab0233c-3f65-11e5-96e0-7171dce2d2d1.png)

**Comment by remram44** [comment] 2015-10-20 18:25
This is because the only time the module is sized is in setupModule(). Then connections get added...

**Comment by rexissimus** [comment] 2015-12-22 17:09
I cannot reproduce this, e.g., a PythonSource with many portspecs seems to resize correctly when loaded. Is there something different with what you are doing?

**Comment by remram44** [comment] 2015-12-22 18:40
The ports are optional but connected.

**Comment by rexissimus** [comment] 2015-12-23 15:14
Fixed by 472dee23f5bbf4917db5b9ddf7ba3b345ca48fbc. At some point (01ed7a6566b3e3a0b35053179e84babcc9dc2a0b, e40295454a403f28fdc4352c4721c432b83339d1) we switched from using ``portVisible`` to using ``visible_input_ports`` and ``visible_output_ports``, but this was only partially completed. I have now removed all references to ``portVisible`` and everything seems to work correctly.

**Comment by remram44** [comment] 2015-12-28 15:12
I can still run into this by using the "save as" feature, though I confirm that it doesn't happen anymore on load.

![Reproduction](https://cloud.githubusercontent.com/assets/426784/12020522/ac27f47a-ad7d-11e5-8826-0a860178a27b.gif)

**Comment by rexissimus** [comment] 2015-12-28 16:27
That is strange. The "save as" must be updating the pipeline in some different way. I will investigate.

**Comment by rexissimus** [comment] 2015-12-28 17:13
Fixed by  e21695a7388e7d15a06cd9e7c3b5d36ecaa1b6a0. 'Save as' creates a new pipeline, but no new connections are added so the ports were not marked as visible.

**Closed by rexissimus** 2015-12-28 17:13 UTC
Labels: C-gui, C-pipeline, S-minor, T-bug
