### ISSUE TITLE
API for Provenance of Interaction

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#801] opened 2013-12-04 23:07 UTC
Currently, we have methods to capture interaction provenance for specific cases (e.g. the save camera for VTK, DV3D methods), but we should consider a general interface for any spreadsheet cell to publish provenance and/or update workflows based on user interactions with the cells.

**Comment by remram44** [comment] 2015-04-28 17:45
Duplicate of #807

**Closed by remram44** 2015-04-28 17:45 UTC
Labels: +enhancement, core, _major
