### ISSUE TITLE
Abstractions don't work

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1065] opened 2015-04-25 19:18 UTC
Do we have any test for these?

Reported by Matthias Troyer

```
Traceback (most recent call last):
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/vistrails_window.py", line 1942, in method
    getattr(obj, method_name)()
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/vistrail_view.py", line 1087, in execute
    view.execute()
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/pipeline_view.py", line 3602, in execute
    self.controller.execute_user_workflow()
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/vistrail_controller.py", line 444, in execute_user_workflow
    result =  self.execute_current_workflow(reason=reason, sinks=sinks)
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/vistrail_controller.py", line 415, in execute_current_workflow
    extra_info)])
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/gui/vistrail_controller.py", line 369, in execute_workflow_list
    vistrails)        
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/core/vistrail/controller.py", line 2635, in execute_workflow_list
    result = interpreter.execute(pipeline, **kwargs)
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/core/interpreter/cached.py", line 730, in execute
    res = self.setup_pipeline(pipeline, **new_kwargs)
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/core/interpreter/cached.py", line 361, in setup_pipeline
    obj = self._objects[persistent_id] = module.summon()
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/core/vistrail/module.py", line 303, in summon
    result.transfer_attrs(self)
  File "/Users/remirampin/Documents/programming/dat/vistrails/vistrails/core/modules/sub_module.py", line 236, in transfer_attrs
    if module._port_specs is None:
AttributeError: 'Abstraction' object has no attribute '_port_specs'
```

**Comment by remram44** [comment] 2015-04-27 04:59
The next 2.2.y release should probably have a fix for this, it's really critical.

**Comment by vistrails-dev** [comment] 2015-04-27 05:51
I will then also contribute a new version of ALPS, thus please let me know when this is planned.

**Comment by vistrails-dev** [comment] 2015-04-27 06:21
My only test is trying to launch an ALPS workflow. I'll try to create a simple one.

**Comment by rexissimus** [comment] 2015-04-27 13:05
One test is in gui/vistrail_controller.py: test_abstraction_create. But we never try to execute it. I am not sure we have any examples with abstractions.

transfer_attrs is a new method. It was probably never tested with subworkflows. It may be enough to initialize _port_specs in core/vistrail/abstraction.py, but I am not sure.

**Comment by rexissimus** [comment] 2015-04-27 13:12
We want to release this ASAP but can probably hold off a few days for ALPS. Otherwise we can make an additional release once ALPS is ready.

**Comment by rexissimus** [comment] 2015-04-27 14:07
The code below works. It looks like transfer_attrs does not need to copy the port specs for Abstractions?

    diff vistrails/core/modules/sub_module.py
    @@ -336,6 +336,10 @@ class Abstraction(Group):
         def __init__(self):
             Group.__init__(self)
  
    +    def transfer_attrs(self, module):
    +        self.pipeline = module.pipeline
    +        Module.transfer_attrs(self, module)

**Comment by vistrails-dev** [comment] 2015-04-27 14:09
I can have an ALPS version for MacOS ready within a day once I test it. 

It’s not urgent since we can always post an ALPS patch for VisTrails

Matthias

**Comment by rexissimus** [comment] 2015-04-27 17:27
This should be fixed. I also added a test so that it does not happen again.

**Comment by remram44** [comment] 2015-04-27 18:12
#725 is pretty serious as well.

**Closed** 2015-04-27 18:14 UTC
Labels: +bug, @pending-review, core, _critical

**Comment by vistrails-dev** [comment] 2015-04-28 13:19
I pulled the changes and now I get a different error, again just trying to run an ALPS workflow. Still, the workflow does not even start executing.

Matthias


Traceback (most recent call last):
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrails_window.py", line 1942, in method
getattr(obj, method_name)()
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrail_view.py", line 1087, in execute
view.execute()
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/pipeline_view.py", line 3602, in execute
self.controller.execute_user_workflow()
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrail_controller.py", line 483, in execute_user_workflow
result = self.execute_current_workflow(reason=reason, sinks=sinks)
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrail_controller.py", line 454, in execute_current_workflow
extra_info)])
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrail_controller.py", line 408, in execute_workflow_list
vistrails)
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/core/vistrail/controller.py", line 2631, in execute_workflow_list
result = interpreter.execute(pipeline, **kwargs)
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/core/interpreter/cached.py", line 730, in execute
res = self.setup_pipeline(pipeline, **new_kwargs)
File "/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/core/interpreter/cached.py", line 434, in setup_pipeline
tmp_id_to_module_map[i] = self._objects[j]
KeyError: -23

**Comment by rexissimus** [comment] 2015-04-28 13:28
Can you upload the workflow you are running? This may be a different problem with SubWorkflow or Map.

**Comment by vistrails-dev** [comment] 2015-04-28 13:50
You will unfortunately need to install the ALPS applications to see the problem. Any version of ALPS should work. I could not yet simplify it to something which does not need them. The problem goes away when I remove the persistence modules. I also attach a new version of the alps package which fixes compatibility issues during initialization.

**Comment by rexissimus** [comment] 2015-04-28 14:22
Thanks. But I am not able to reproduce your problem. For me, "local updates" works, and "cluster updates" gives an error in the SubWorkflow:

    Traceback (most recent call last):
      File "vistrails/core/modules/vistrails_module.py", line 573, in update
      File "vistrails/packages/matplotlib/bases.py", line 107, in compute
    TypeError: 'MplXYPlot' object is not callable

Did you try to "git clean" the .pyc files in your installation?

**Comment by rexissimus** [comment] 2015-04-28 14:56
The matplotlib issue is caused by a change in the matplotlib package. MplFigure now takes a callable that generates the plot. You can look in `vistrails/packages/matplotlib/bases.py` for how this works.

**Comment by vistrails-dev** [comment] 2015-04-28 15:16
I'll try again removing the pyc files. Just to confirm: which branch should I pull from?

**Comment by rexissimus** [comment] 2015-04-28 15:17
v2.2 has all latest changes.

**Comment by vistrails-dev** [comment] 2015-04-28 15:27
I don’t see that branch. Do I use a wrong repository?

**Comment by rexissimus** [comment] 2015-04-28 15:31
We have moved to github: https://github.com/VisTrails/VisTrails/tree/v2.2

We mirror to the old repo nightly, but it is possible the v2.2 branch is not included yet.

**Comment by vistrails-dev** [comment] 2015-04-28 15:33
Thank you, I’ll try with that

Matthias

**Comment by vistrails-dev** [comment] 2015-04-29 20:13
Indeed, with that version the workflows now start executing. Thank you!
